# Generated by Django 2.2 on 2021-07-30 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200, unique=True)),
                ('cat_slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_name', models.CharField(max_length=250, unique=True)),
                ('P_slug', models.SlugField(max_length=250, unique=True)),
                ('P_desc', models.TextField()),
                ('P_price', models.IntegerField()),
                ('P_stock', models.IntegerField()),
                ('P_available', models.BooleanField()),
                ('P_image', models.ImageField(upload_to='Product')),
                ('P_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category')),
            ],
        ),
    ]
