# Generated by Django 2.2 on 2021-07-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210730_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('cat_name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
